# Generated by Django 5.0.2 on 2024-11-30 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directs', '0004_videocalllog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoCallLog',
        ),
    ]
