# Generated by Django 5.0.2 on 2025-01-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directs', '0005_delete_videocalllog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.CharField(default='', max_length=100),
        ),
    ]
