# Generated by Django 5.0.2 on 2024-11-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0007_auto_20240816_0910'),
        ('post', '0005_auto_20220208_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favourite',
            field=models.ManyToManyField(to='post.post'),
        ),
    ]
