# Generated by Django 5.0.2 on 2024-11-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0008_alter_profile_favourite'),
        ('post', '0006_post_likers_post_savers_delete_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favourite',
            field=models.ManyToManyField(blank=True, to='post.post'),
        ),
    ]
