# Generated by Django 5.0.2 on 2025-01-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0010_profile_interests_profile_role_profile_skills_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', null=True, upload_to='profile_pciture'),
        ),
    ]
