# Generated by Django 5.0.2 on 2025-01-08 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0011_alter_profile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='learner',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='mentor',
        ),
        migrations.AddField(
            model_name='rating',
            name='rate_type',
            field=models.CharField(choices=[('mentor', 'Mentor'), ('learner', 'Learner')], default='mentor', max_length=10),
        ),
        migrations.AddField(
            model_name='rating',
            name='rated_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='reviewer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
